// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {desktopapp} from '../models';

export function Activate():Promise<void>;

export function ApplyUpdate():Promise<void>;

export function AutostartEnabled():Promise<boolean>;

export function CancelJob(arg1:string):Promise<void>;

export function CheckForUpdate():Promise<string>;

export function Enroll(arg1:string):Promise<void>;

export function GetState():Promise<desktopapp.StateDTO>;

export function InstallApp():Promise<string>;

export function IsAppInstalled():Promise<boolean>;

export function PauseAll():Promise<void>;

export function PauseJob(arg1:string):Promise<void>;

export function ReprintJob(arg1:string):Promise<void>;

export function ResumeJob(arg1:string):Promise<void>;

export function SetAutoUpdate(arg1:boolean):Promise<void>;

export function SetAutostart(arg1:boolean):Promise<void>;

export function SetDefaultPrinter(arg1:string):Promise<void>;

export function SetNotifyDone(arg1:boolean):Promise<void>;

export function SetNotifyFailed(arg1:boolean):Promise<void>;

export function SetNotifyWeekly(arg1:boolean):Promise<void>;

export function SetServer(arg1:string):Promise<void>;

export function SetTheme(arg1:string):Promise<void>;

export function SetToken(arg1:string):Promise<void>;

export function UninstallApp():Promise<void>;
