// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Activate() {
  return window['go']['desktopapp']['App']['Activate']();
}

export function ApplyUpdate() {
  return window['go']['desktopapp']['App']['ApplyUpdate']();
}

export function AutostartEnabled() {
  return window['go']['desktopapp']['App']['AutostartEnabled']();
}

export function CancelJob(arg1) {
  return window['go']['desktopapp']['App']['CancelJob'](arg1);
}

export function CheckForUpdate() {
  return window['go']['desktopapp']['App']['CheckForUpdate']();
}

export function Enroll(arg1) {
  return window['go']['desktopapp']['App']['Enroll'](arg1);
}

export function GetState() {
  return window['go']['desktopapp']['App']['GetState']();
}

export function InstallApp() {
  return window['go']['desktopapp']['App']['InstallApp']();
}

export function IsAppInstalled() {
  return window['go']['desktopapp']['App']['IsAppInstalled']();
}

export function PauseAll() {
  return window['go']['desktopapp']['App']['PauseAll']();
}

export function PauseJob(arg1) {
  return window['go']['desktopapp']['App']['PauseJob'](arg1);
}

export function ReprintJob(arg1) {
  return window['go']['desktopapp']['App']['ReprintJob'](arg1);
}

export function ResumeJob(arg1) {
  return window['go']['desktopapp']['App']['ResumeJob'](arg1);
}

export function SetAutoUpdate(arg1) {
  return window['go']['desktopapp']['App']['SetAutoUpdate'](arg1);
}

export function SetAutostart(arg1) {
  return window['go']['desktopapp']['App']['SetAutostart'](arg1);
}

export function SetDefaultPrinter(arg1) {
  return window['go']['desktopapp']['App']['SetDefaultPrinter'](arg1);
}

export function SetNotifyDone(arg1) {
  return window['go']['desktopapp']['App']['SetNotifyDone'](arg1);
}

export function SetNotifyFailed(arg1) {
  return window['go']['desktopapp']['App']['SetNotifyFailed'](arg1);
}

export function SetNotifyWeekly(arg1) {
  return window['go']['desktopapp']['App']['SetNotifyWeekly'](arg1);
}

export function SetServer(arg1) {
  return window['go']['desktopapp']['App']['SetServer'](arg1);
}

export function SetTheme(arg1) {
  return window['go']['desktopapp']['App']['SetTheme'](arg1);
}

export function SetToken(arg1) {
  return window['go']['desktopapp']['App']['SetToken'](arg1);
}

export function UninstallApp() {
  return window['go']['desktopapp']['App']['UninstallApp']();
}
